# chmod -R 777 /home/guowm/data/elk/elasticsearch/data
version: '3.0'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    restart: always
    container_name: kibana-7.9.3
    ports:
      - 5602:5601
    environment:
      ELASTICSEARCH_HOSTS: http://192.168.85.125:9201
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    restart: always
    container_name: elasticsearch-7.9.3
    ports:
      - 9201:9200
      - 9301:9300
    environment:
      discovery.type: single-node
      network.host: 0.0.0.0
    privileged: true
    volumes:
      - /home/guowm/data/elk/elasticsearch/data:/usr/share/elasticsearch/data
